"""Markdown parser that extracts structured sections."""

from __future__ import annotations

import re
from dataclasses import dataclass, field

from markdown_it import MarkdownIt
from markdown_it.token import Token

from services.readme_cleaning.html_normalizer import html_token_to_text
from services.readme_cleaning.models import ReadmeSection
from services.readme_cleaning.text_normalizer import normalize_inline_markdown_text, squeeze_blank_lines


@dataclass
class _SectionBuilder:
    heading: str
    level: int | None
    lines: list[str] = field(default_factory=list)
    source_kinds: set[str] = field(default_factory=lambda: {"paragraph"})

    def add_line(self, text: str, kind: str = "paragraph") -> None:
        value = (text or "").strip("\n")
        if not value:
            return
        self.lines.append(value)
        self.source_kinds.add(kind)

    def build(self) -> ReadmeSection | None:
        body = squeeze_blank_lines("\n".join(self.lines))
        if not body and not self.heading:
            return None
        full_text = f"{self.heading}\n{body}".strip()
        source_kind = "mixed" if len(self.source_kinds) > 1 else next(iter(self.source_kinds))
        return ReadmeSection(
            heading=self.heading or "Overview",
            level=self.level,
            body=body,
            text=full_text,
            source_kind=source_kind,
        )


def _extract_inline_text(inline_token: Token) -> str:
    if not inline_token.children:
        return normalize_inline_markdown_text(inline_token.content or "")

    parts: list[str] = []
    for child in inline_token.children:
        if child.type in {"text", "code_inline"}:
            parts.append(child.content or "")
        elif child.type in {"softbreak", "hardbreak"}:
            parts.append("\n")
        elif child.type == "image":
            if child.content:
                parts.append(child.content)
        elif child.type == "html_inline":
            html_text = html_token_to_text(child.content or "")
            if html_text:
                parts.append(html_text)
        elif child.content:
            parts.append(child.content)
    return normalize_inline_markdown_text(" ".join(parts))


def _is_setext_line(line: str) -> bool:
    return bool(re.match(r"^\s*(=+|-+)\s*$", line))


def parse_readme_sections(markdown_text: str) -> list[ReadmeSection]:
    """Parse markdown into logical sections using markdown-it token stream."""
    md = MarkdownIt("commonmark")
    tokens = md.parse(markdown_text or "")
    sections: list[ReadmeSection] = []
    current = _SectionBuilder(heading="Overview", level=None)

    i = 0
    while i < len(tokens):
        token = tokens[i]
        if token.type == "heading_open":
            built = current.build()
            if built:
                sections.append(built)
            level = int(token.tag[-1]) if token.tag and token.tag[-1].isdigit() else None
            heading_text = ""
            if i + 1 < len(tokens) and tokens[i + 1].type == "inline":
                heading_text = _extract_inline_text(tokens[i + 1]).strip() or "Untitled"
            current = _SectionBuilder(heading=heading_text, level=level, source_kinds={"paragraph"})
            i += 1
        elif token.type == "inline":
            text = _extract_inline_text(token)
            if text and not _is_setext_line(text):
                if token.map and token.level > 0:
                    current.add_line(text, kind="list")
                else:
                    current.add_line(text, kind="paragraph")
        elif token.type == "fence":
            info = (token.info or "").strip().split()[0] if token.info else ""
            code = (token.content or "").rstrip()
            current.add_line(f"```{info}\n{code}\n```", kind="code")
        elif token.type == "code_block":
            current.add_line(f"```\n{(token.content or '').rstrip()}\n```", kind="code")
        elif token.type in {"html_block", "html_inline"}:
            html_text = html_token_to_text(token.content or "")
            if html_text:
                current.add_line(html_text, kind="paragraph")
        i += 1

    built = current.build()
    if built:
        sections.append(built)

    # Remove empty sections generated by token boundaries.
    return [sec for sec in sections if sec.body.strip() or sec.heading.strip()]
